os:
  - linux
language: node_js
node_js:
  - '12.14.1'
cache:
  yarn: true
  directories:
    - node
    - node_modules
env:
  global:
    - NODE_VERSION=12.14.1
    - YARN_VERSION=1.21.1-1
before_install:
  - nvm install $NODE_VERSION
  - node -v
    # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=$YARN_VERSION
install:
  - yarn install
script:
  - yarn test
notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
